version: "3"
services:
  node:
    build:
      context: ../../
      dockerfile: docker/chainnode/Dockerfile
    restart: always
    hostname: node
    container_name: node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ~/.skymavis/fchain:/opt/fchain
    environment:
      - SYNC_MODE=${SYNC_MODE}
      - BOOTNODES=${BOOTNODES}
      - NETWORK_ID=${NETWORK_ID}
      - GENESIS_PATH=${GENESIS_PATH}
      - RPC_NODE=${RPC_NODE}
      - DATA_DIR=${DATA_DIR}
      - SUBSCRIBER=${SUBSCRIBER}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_AUTHENTICATION_TYPE=${KAFKA_AUTHENTICATION_TYPE}
      - VERBOSITY=${VERBOSITY}
      - CONFIRM_BLOCK_AT=${CONFIRM_BLOCK_AT}
      - FCHAIN_PARAMS=${FCHAIN_PARAMS}
      - MINE=${MINE}
    network_mode: bridge
